#!/bin/bash
set -euo pipefail

readonly url="https://github.com/privacy-scaling-explorations/snark-artifacts/raw/main/artifacts"
declare -a pids
declare -A urls
declare -A filenames

dl() {
  local filename=$1
  curl -LSs -o "$filename" "$url/$artifact" &
  pid=$!
  pids+=("$pid")
  urls[$pid]="$url/$artifact"
  filenames[$pid]="$filename"
}

check() {
  for pid in "${pids[@]}"; do
    wait "$pid"
    exit_code=$?

    if [ $exit_code -ne 0 ]; then
      echo "Failed to download ${urls[$pid]}"
      exit 1
    fi

    if [ ! -s "${filenames[$pid]}" ]; then
      echo "Downloaded ${filenames[$pid]} is empty"
      exit 1
    fi

    echo "Downloaded ${urls[$pid]}"
  done

}

main() {
  for artifact in {eddsa,poseidon-{1..16},semaphore-{1..12}}.{wasm,zkey}; do
    dl "$artifact"
  done
  check
}

main
